### ISSUE TITLE
能否在自己朋友圈时间线上直接显示 deleted

### ISSUE THREAD

**Issue by ivysrono** [rarnu/wechat_no_revoke#1]
1.0 版只能在单独查看对方朋友圈时显示。

**Comment by rarnu** [comment]
暂未考虑朋友圈的问题，你应该是安装了其他的插件才显示朋友圈的已删

**Comment by ivysrono** [comment]
repo.xposed.info/module/com.fkzhang.wechatunrecalled
卸载了这个，以前的deleted还能继续显示？好神奇……
