### ISSUE TITLE
微信打不开

### ISSUE THREAD

**Issue by ghost** [rarnu/wechat_no_revoke#2]
nexus 6p 原版6.0.1 微信6.5.3
没有装其它和微信有关的xposed模块

**Comment by rarnu** [comment]
能否帮忙抓个log?

**Comment by ghost** [comment]
是这个吗

01-15 02:07:38.093 I/Xposed  (  527): -----------------01-15 02:07:38.093 I/Xposed  (  527): Starting Xposed version 87, compiled for SDK 2301-15 02:07:38.093 I/Xposed  (  527): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)01-15 02:07:38.093 I/Xposed  (  527): ROM: MTC20L01-15 02:07:38.093 I/Xposed  (  527): Build fingerprint: google/angler/angler:6.0.1/MTC20L/3230295:user/release-keys01-15 02:07:38.093 I/Xposed  (  527): Platform: arm64-v8a, 64-bit binary, system server: yes01-15 02:07:38.093 I/Xposed  (  527): SELinux enabled: yes, enforcing: yes01-15 02:07:38.110 I/Xposed  (  527): -----------------01-15 02:07:38.112 I/Xposed  (  527): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH01-15 02:07:38.540 I/Xposed  (  527): Detected ART runtime01-15 02:07:38.554 I/Xposed  (  527): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing01-15 02:07:38.924 I/Xposed  (  527): Loading modules from /data/app/com.ghostflying.locationreportenabler-1/base.apk01-15 02:07:38.935 I/Xposed  (  527):   Loading class com.ghostflying.locationreportenabler.Main01-15 02:07:38.936 I/Xposed  (  527): Loading modules from /data/app/com.rarnu.norevoke-1/base.apk01-15 02:07:38.953 I/Xposed  (  527):   Loading class com.rarnu.norevoke.xposed.XpWechat01-15 02:07:48.278 I/Xposed  (  528): -----------------01-15 02:07:48.279 I/Xposed  (  528): Starting Xposed version 87, compiled for SDK 2301-15 02:07:48.279 I/Xposed  (  528): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)01-15 02:07:48.279 I/Xposed  (  528): ROM: MTC20L01-15 02:07:48.279 I/Xposed  (  528): Build fingerprint: google/angler/angler:6.0.1/MTC20L/3230295:user/release-keys01-15 02:07:48.279 I/Xposed  (  528): Platform: arm64-v8a, 32-bit binary, system server: no01-15 02:07:48.279 I/Xposed  (  528): SELinux enabled: yes, enforcing: yes01-15 02:07:48.284 I/Xposed  (  528): -----------------01-15 02:07:48.284 I/Xposed  (  528): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH01-15 02:07:48.568 I/Xposed  (  528): Detected ART runtime01-15 02:07:48.580 I/Xposed  (  528): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing01-15 02:07:48.874 I/Xposed  (  528): Loading modules from /data/app/com.ghostflying.locationreportenabler-1/base.apk01-15 02:07:48.880 I/Xposed  (  528):   Loading class com.ghostflying.locationreportenabler.Main01-15 02:07:48.881 I/Xposed  (  528): Loading modules from /data/app/com.rarnu.norevoke-1/base.apk01-15 02:07:48.893 I/Xposed  (  528):   Loading class com.rarnu.norevoke.xposed.XpWechat01-15 02:08:31.482 W/Xposed  ( 4282): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:10:03.694 W/Xposed  ( 8310): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:07:38.093 I/Xposed  (  527): -----------------01-15 02:07:38.093 I/Xposed  (  527): Starting Xposed version 87, compiled for SDK 2301-15 02:07:38.093 I/Xposed  (  527): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)01-15 02:07:38.093 I/Xposed  (  527): ROM: MTC20L01-15 02:07:38.093 I/Xposed  (  527): Build fingerprint: google/angler/angler:6.0.1/MTC20L/3230295:user/release-keys01-15 02:07:38.093 I/Xposed  (  527): Platform: arm64-v8a, 64-bit binary, system server: yes01-15 02:07:38.093 I/Xposed  (  527): SELinux enabled: yes, enforcing: yes01-15 02:07:38.110 I/Xposed  (  527): -----------------01-15 02:07:38.112 I/Xposed  (  527): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH01-15 02:07:38.540 I/Xposed  (  527): Detected ART runtime01-15 02:07:38.554 I/Xposed  (  527): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing01-15 02:07:38.924 I/Xposed  (  527): Loading modules from /data/app/com.ghostflying.locationreportenabler-1/base.apk01-15 02:07:38.935 I/Xposed  (  527):   Loading class com.ghostflying.locationreportenabler.Main01-15 02:07:38.936 I/Xposed  (  527): Loading modules from /data/app/com.rarnu.norevoke-1/base.apk01-15 02:07:38.953 I/Xposed  (  527):   Loading class com.rarnu.norevoke.xposed.XpWechat01-15 02:07:48.278 I/Xposed  (  528): -----------------01-15 02:07:48.279 I/Xposed  (  528): Starting Xposed version 87, compiled for SDK 2301-15 02:07:48.279 I/Xposed  (  528): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)01-15 02:07:48.279 I/Xposed  (  528): ROM: MTC20L01-15 02:07:48.279 I/Xposed  (  528): Build fingerprint: google/angler/angler:6.0.1/MTC20L/3230295:user/release-keys01-15 02:07:48.279 I/Xposed  (  528): Platform: arm64-v8a, 32-bit binary, system server: no01-15 02:07:48.279 I/Xposed  (  528): SELinux enabled: yes, enforcing: yes01-15 02:07:48.284 I/Xposed  (  528): -----------------01-15 02:07:48.284 I/Xposed  (  528): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH01-15 02:07:48.568 I/Xposed  (  528): Detected ART runtime01-15 02:07:48.580 I/Xposed  (  528): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing01-15 02:07:48.874 I/Xposed  (  528): Loading modules from /data/app/com.ghostflying.locationreportenabler-1/base.apk01-15 02:07:48.880 I/Xposed  (  528):   Loading class com.ghostflying.locationreportenabler.Main01-15 02:07:48.881 I/Xposed  (  528): Loading modules from /data/app/com.rarnu.norevoke-1/base.apk01-15 02:07:48.893 I/Xposed  (  528):   Loading class com.rarnu.norevoke.xposed.XpWechat01-15 02:08:31.482 W/Xposed  ( 4282): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:10:03.694 W/Xposed  ( 8310): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:11:30.277 W/Xposed  ( 9572): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:07:38.093 I/Xposed  (  527): -----------------01-15 02:07:38.093 I/Xposed  (  527): Starting Xposed version 87, compiled for SDK 2301-15 02:07:38.093 I/Xposed  (  527): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)01-15 02:07:38.093 I/Xposed  (  527): ROM: MTC20L01-15 02:07:38.093 I/Xposed  (  527): Build fingerprint: google/angler/angler:6.0.1/MTC20L/3230295:user/release-keys01-15 02:07:38.093 I/Xposed  (  527): Platform: arm64-v8a, 64-bit binary, system server: yes01-15 02:07:38.093 I/Xposed  (  527): SELinux enabled: yes, enforcing: yes01-15 02:07:38.110 I/Xposed  (  527): -----------------01-15 02:07:38.112 I/Xposed  (  527): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH01-15 02:07:38.540 I/Xposed  (  527): Detected ART runtime01-15 02:07:38.554 I/Xposed  (  527): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing01-15 02:07:38.924 I/Xposed  (  527): Loading modules from /data/app/com.ghostflying.locationreportenabler-1/base.apk01-15 02:07:38.935 I/Xposed  (  527):   Loading class com.ghostflying.locationreportenabler.Main01-15 02:07:38.936 I/Xposed  (  527): Loading modules from /data/app/com.rarnu.norevoke-1/base.apk01-15 02:07:38.953 I/Xposed  (  527):   Loading class com.rarnu.norevoke.xposed.XpWechat01-15 02:07:48.278 I/Xposed  (  528): -----------------01-15 02:07:48.279 I/Xposed  (  528): Starting Xposed version 87, compiled for SDK 2301-15 02:07:48.279 I/Xposed  (  528): Device: Nexus 6P (Huawei), Android version 6.0.1 (SDK 23)01-15 02:07:48.279 I/Xposed  (  528): ROM: MTC20L01-15 02:07:48.279 I/Xposed  (  528): Build fingerprint: google/angler/angler:6.0.1/MTC20L/3230295:user/release-keys01-15 02:07:48.279 I/Xposed  (  528): Platform: arm64-v8a, 32-bit binary, system server: no01-15 02:07:48.279 I/Xposed  (  528): SELinux enabled: yes, enforcing: yes01-15 02:07:48.284 I/Xposed  (  528): -----------------01-15 02:07:48.284 I/Xposed  (  528): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH01-15 02:07:48.568 I/Xposed  (  528): Detected ART runtime01-15 02:07:48.580 I/Xposed  (  528): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing01-15 02:07:48.874 I/Xposed  (  528): Loading modules from /data/app/com.ghostflying.locationreportenabler-1/base.apk01-15 02:07:48.880 I/Xposed  (  528):   Loading class com.ghostflying.locationreportenabler.Main01-15 02:07:48.881 I/Xposed  (  528): Loading modules from /data/app/com.rarnu.norevoke-1/base.apk01-15 02:07:48.893 I/Xposed  (  528):   Loading class com.rarnu.norevoke.xposed.XpWechat01-15 02:08:31.482 W/Xposed  ( 4282): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:10:03.694 W/Xposed  ( 8310): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:11:30.277 W/Xposed  ( 9572): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:13:23.106 W/Xposed  (10959): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:15:53.450 W/Xposed  (11586): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:16:52.974 W/Xposed  (11940): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser01-15 02:17:02.108 W/Xposed  (12101): Package name for /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser

**Comment by rarnu** [comment]
这个log显示是正常的，都正常加载，但是似乎你的问题不是这个。
麻烦尝试下抓取在点击打开微信时的log，并且不要开启Xposed关键字过滤

**Comment by lanshifu** [comment]
大神你是用c++写的呀，感觉牛逼哄哄，想看下核心代码，拦截哪一个方法，没看懂><

**Comment by rarnu** [comment]
@lanshifu 程序是采用kotlin开发的，不是C++
拦截的方法看WechatVersion里面代码，由于微信每个版本都会做混淆，因此这部分是变化的，除此之外勾子的代码在WechatRevokeHook内hookRevoke方法

另，你起的话题与题主不同，下次请开新issue

**Comment by Gh0u1L5** [comment]
@freezex 讲道理，微信crash的话你应该考虑抓一下logcat的内容

**Comment by moncat** [comment]
楼主解决这个问题了吗？ 感觉是xposed 不支持 补丁包  /data/user/0/com.tencent.mm/tinker/patch-6f6e6e23/res/resources.apk had to be retrieved via parser的问题，解决了分享一下啊。
